
CREATE OR REPLACE TEMPORARY TABLE TMP_EXPOSURES_ONDEMAND AS (
SELECT
	CAMPAIGN
        , PRODUCT
        , CHANNEL
        , CLIENT_NAME
        , CLIENT_ID
        , GEOGRAPHY
        , BGID
        , STATION
        , SPOT_ID
        , SPOT_NAME
        , SPOT_LENGTH
        , TO_CHAR(SPOT_START_TS_UTC,'YYYY-MM-DD HH24:MI:SS') AS SPOT_START_TS_UTC
        , SPOT_LOCAL_UTC_OFFSET
        , TO_CHAR(VIEWERSHIP_START_TS_UTC,'YYYY-MM-DD HH24:MI:SS') AS VIEWERSHIP_START_TS_UTC
FROM ${TD_DATABASE_AM_XTR}.AM_TV_SQUARED_EXTRACT_SPOT
WHERE LD_SEQ_NBR = (SELECT MAX(LD_SEQ_NBR) FROM ${TD_DATABASE_AM_XTR}.AM_TV_SQUARED_EXTRACT_SPOT)
);

CREATE TEMPORARY STAGE IF NOT EXISTS TMP_STG_EXPOSURES_ONDEMAND;

COPY INTO @TMP_STG_EXPOSURES_ONDEMAND/unload/
FROM TMP_EXPOSURES_ONDEMAND
FILE_FORMAT = (
TYPE=CSV
COMPRESSION=GZIP
EMPTY_FIELD_AS_NULL = false
NULL_IF = ('')
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
ESCAPE = '0x22')
single = false
max_file_size=4900000000;

GET @TMP_STG_EXPOSURES_ONDEMAND/unload/ file://${v_ExtractDir}/sf_transition/;
